[build]
  publish = "/"

# Optimize caching for static assets
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Specific headers for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
# Optimize JavaScript files
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "application/javascript; charset=utf-8"

# Optimize CSS files
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "text/css; charset=utf-8"
